-- CTAS TABLE

USE ORGANISATION;

CREATE TABLE HIGH_PAID_EMPLOYEES AS
SELECT 
     EMPLOYEE_ID,
     FIRST_NAME,
     LAST_NAME,
     SALARY
FROM EMPLOYEES
WHERE SALARY > 15000 ;

SELECT * FROM HIGH_PAID_EMPLOYEES;

-- NORMAL TABLE 
USE AP_DS_TEST;

CREATE TABLE TEST2 (
              
           ID INT PRIMARY KEY,
           EMPLOYEE_NAME VARCHAR(100),
           SALARY INT
)

SELECT * FROM TEST2;


-- TEMPORARY TABLE
-- CREATE TEMP TABLE
CREATE TEMPORARY TABLE TEMP_HIGH_PAID_EMPLOYEES (
                                              EMPLOYEE_ID INT PRIMARY KEY,
                                              SALARY INT
 );
 
 -- INSERT DATA
INSERT INTO  TEMP_HIGH_PAID_EMPLOYEES 
SELECT 
     EMPLOYEE_ID,
     SALARY
FROM EMPLOYEES
WHERE SALARY > 15000 ;

 -- VIEW DATA
SELECT * FROM TEMP_HIGH_PAID_EMPLOYEES

-- DROP IF TABLE ALREADY EXIST
DROP TABLE TEMP_HIGH_PAID_EMPLOYEES;



-- CTAS PRACTICE

USE ORG;

CREATE TABLE MOST_HIGH_PAID_EMPLOYEES AS
SELECT
      EMP_ID,
      EMP_NAME,
      SALARY
FROM EMPLOYEE
WHERE SALARY > 400000;

-- UPDATE

UPDATE MOST_HIGH_PAID_EMPLOYEES
SET SALARY = SALARY + 5000
WHERE SALARY > 100000;

-- VIEW TABLE

SELECT * FROM MOST_HIGH_PAID_EMPLOYEES

-- TABLE EXIST
DROP TABLE MOST_HIGH_PAID_EMPLOYEES