CREATE SCHEMA TEST;
USE TEST;
CREATE TABLE STUDENT

( STU_ID INT PRIMARY KEY,
  NAME VARCHAR (30),
  MARK INT
)

INSERT INTO STUDENT(STU_ID,NAME,MARK) VALUE (1,"ARUL",99)
INSERT INTO STUDENT (STU_ID,NAME,MARK)VALUE (2,"VASI",98)

SELECT * FROM STUDENT;

CREATE DATABASE COMPANY;

USE COMPANY;

CREATE SCHEMA WORKER_DETAILS;

CREATE TABLE HR(
HR_ID INT auto_increment PRIMARY KEY,
NAME VARCHAR (50),
SALARY INT 
)

CREATE TABLE WORKER(
WORKER_ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(50),
SALARY INT
)

CREATE TABLE HR_INCREMENT(
    HR_ID INT,
    NAME VARCHAR(50),
    FOREIGN KEY (HR_ID) REFERENCES HR(HR_ID)
);
SELECT * FROM WORKER_DETAILS

SELECT * FROM hr;
SELECT * FROM worker;
SELECT * FROM HR_INCREMENT; 

INSERT INTO HR VALUE(1,"ARUL",20000);
INSERT INTO HR VALUE(2,"VINNU",300000);
INSERT INTO HR VALUE(3,"MUKIL",400000);

SHOW DATABASES;

DROP DATABASE SAKILA;


CREATE DATABASE AP_DS_TEST;
USE AP_DS_TEST;
CREATE TABLE TEST1 (
             SNO INT,
             NAME VARCHAR(100)
);
SELECT * FROM TEST1;
INSERT INTO TEST1(SNO,NAME) VALUES (1,'ARUL');
INSERT INTO TEST1(SNO,NAME) VALUES (2,'BHARATHI');
INSERT INTO TEST1(SNO,NAME) VALUE (3,'AMUDHA');
INSERT INTO TEST1 (SNO,NAME) VALUE (4,'JAYASREE');
INSERT INTO TEST1 (SNO,NAME) VALUE (6,'MUKILAN');
INSERT INTO TEST1 (SNO,NAME) VALUE (6,'JEEVAN');

UPDATE TEST1 SET NAME= 'ARULPRASATH' WHERE SNO = 1;
UPDATE TEST1 SET NAME = 'JAYABHARATHI' WHERE SNO = 2; 
UPDATE TEST1 SET  NAME = 'AMUDHABALAN' WHERE SNO = 3;
UPDATE TEST1 SET NAME = 'MUKIL',SNO = 5 WHERE SNO = 6;

DELETE FROM TEST1 WHERE SNO =6;

TRUNCATE TABLE TEST1;

DROP TABLE TEST1;