USE ORGANISATION;


SELECT *FROM DEPARTMENTS;

ALTER TABLE DEPARTMENTS ADD EMAIL VARCHAR (100);

INSERT INTO (EMAIL) VALUE 'ABC@GMAIL.COM';


USE AP_DS_TEST;

CREATE TABLE TEST3 (
			SNO INT PRIMARY KEY,
            FIRST_NAME VARCHAR(100),
            LAST_NAME VARCHAR (100)
);

SELECT * FROM TEST3;

-- ADD COLUMN USING ALTER

ALTER TABLE TEST3 
ADD EMAIL VARCHAR (100);

-- DROP COLUMN USING ALTER

ALTER TABLE TEST3 DROP column lAST_NAME;

SELECT *FROM TEST3;

-- RENAME USING ALTER

ALTER TABLE TEST3 RENAME TO TESTT3;

SELECT * FROM TEST3;

SELECT *FROM TESTT3;

ALTER TABLE TESTT3 RENAME TO TEST3;