USE UBER;

CREATE TABLE TRIP (
               RIDE_ID INT PRIMARY KEY,
               DRIVER_ID INT NOT NULL,
               RIDER_ID INT NOT NULL,
               PICKUP_LOCATION VARCHAR (100) NOT NULL ,
               DROPOFF_LOCATION VARCHAR (100) NOT NULL ,
               RIDE_DATE DATETIME NOT NULL,
               FARE DECIMAL(10,2) NOT NULL 
);


INSERT INTO TRIP (RIDE_ID,DRIVER_ID,RIDER_ID,PICKUP_LOCATION,DROPOFF_LOCATION,RIDE_DATE,FARE)
VALUE 
(5,125,201,'VELACHERY','T.NAGAR','2024-12-29 08:00:00',500.00);

-- PRIMARY KEY

SELECT * FROM TRIP;


-- COMPOSITE PRIMARY KEY (MORE THAN ONE PRIMARY KEY)
CREATE TABLE TRIP1 (
               RIDE_ID INT,
               DRIVER_ID INT NOT NULL,
               RIDER_ID INT NOT NULL,
               PICKUP_LOCATION VARCHAR (100) NOT NULL ,
               DROPOFF_LOCATION VARCHAR (100) NOT NULL ,
               RIDE_DATE DATETIME NOT NULL,
               FARE DECIMAL(10,2) NOT NULL,
               PRIMARY KEY (RIDE_ID,RIDER_ID)       -- BOTH RIDE ID AND RIDER ID ARE PRIMARY KEY
);


INSERT INTO TRIP1 (RIDE_ID,DRIVER_ID,RIDER_ID,PICKUP_LOCATION,DROPOFF_LOCATION,RIDE_DATE,FARE)
VALUE 
(1,121,200,'KCBT','TAMBARAM','2024-12-29 08:00:00',500.00);
INSERT INTO TRIP1 (RIDE_ID,DRIVER_ID,RIDER_ID,PICKUP_LOCATION,DROPOFF_LOCATION,RIDE_DATE,FARE)
VALUE 
(1,121,201,'KOYEMBADU','K.K NAGAR','2024-12-29 08:00:00',300.00);
INSERT INTO TRIP1 (RIDE_ID,DRIVER_ID,RIDER_ID,PICKUP_LOCATION,DROPOFF_LOCATION,RIDE_DATE,FARE)
VALUE 
(1,121,203,'KCBT','VELACHERRY','2024-12-29 08:00:00',500.00);
INSERT INTO TRIP1 (RIDE_ID,DRIVER_ID,RIDER_ID,PICKUP_LOCATION,DROPOFF_LOCATION,RIDE_DATE,FARE)
VALUE 
(2,121,200,'KCBT','VELACHERRY','2024-12-29 08:00:00',500.00);
INSERT INTO TRIP1 (RIDE_ID,DRIVER_ID,RIDER_ID,PICKUP_LOCATION,DROPOFF_LOCATION,RIDE_DATE,FARE)
VALUE 
(2,121,201,'KCBT','VELACHERRY','2024-12-29 08:00:00',500.00);
INSERT INTO TRIP1 (RIDE_ID,DRIVER_ID,RIDER_ID,PICKUP_LOCATION,DROPOFF_LOCATION,RIDE_DATE,FARE)
VALUE 
(3,121,200,'KKBT','PALPANNAI','2024-12-29 08:00:00',500.00);

SELECT * FROM TRIP1;

-- UNIQUE KEY


USE UBER;

CREATE TABLE  USER (
           USER_ID INT PRIMARY KEY,
           EMAIL_ID VARCHAR (100) UNIQUE
);

INSERT INTO USER (USER_ID,EMAIL_ID) 
VALUE 
(1,'user1@gmail.com');

INSERT INTO USER (USER_ID,EMAIL_ID)
VALUE
(2,'user2@gmail.com');

INSERT INTO USER (USER_ID,EMAIL_ID)
VALUE
(3,NULL);

INSERT INTO USER (USER_ID,EMAIL_ID)
VALUE
(4,NULL);                         -- UNIQUE CAN ALLOW NULL AND DOESN'T ALLOW DUPLICATES

INSERT INTO USER (USER_ID,EMAIL_ID)
VALUE
(NULL,'user5@gmail.com');          -- PRIMARY KEY DOESN'T ALLOW DUPLICATES AND NULL


INSERT INTO USER (USER_ID,EMAIL_ID)
VALUE
(5,'ABC@gmail.com');



SELECT * FROM USER;

-- NOT NULL CONSTRAINTS 

CREATE TABLE TRIP2 (
               RIDE_ID INT PRIMARY KEY,
               DRIVER_ID INT NOT NULL,                     -- not null doesn't acpt the null values
               RIDER_ID INT ,
               PICKUP_LOCATION VARCHAR (100) NOT NULL ,
               DROPOFF_LOCATION VARCHAR (100) NOT NULL ,
               RIDE_DATE DATETIME NOT NULL,
               FARE DECIMAL(10,2) NOT NULL 
);

INSERT INTO TRIP2 (RIDE_ID,DRIVER_ID,RIDER_ID,PICKUP_LOCATION,DROPOFF_LOCATION,RIDE_DATE,FARE)
VALUE 
(1,121,NULL,'KCBT','TAMBARAM','2024-12-29 08:00:00',500.00);             
INSERT INTO TRIP2 (RIDE_ID,DRIVER_ID,RIDER_ID,PICKUP_LOCATION,DROPOFF_LOCATION,RIDE_DATE,FARE)
VALUE 
(2,121,NULL,NULL ,'TAMBARAM','2024-12-29 08:00:00',500.00);       -- IT SHOWS ERROR BCOZ NOT NULL PICKUP_LOCATION HAVE A NULL VALUE

 

INSERT INTO TRIP2 (RIDE_ID,DRIVER_ID,RIDER_ID,PICKUP_LOCATION,DROPOFF_LOCATION,RIDE_DATE,FARE)
VALUE 
(4,121,NULL,'KCBT','TAMBARAM','2024-12-29 08:00:00',500.00);  

DESC TRIP2;

SELECT * FROM TRIP2;

-- CHECK CONSTRAINS

USE UBER;

CREATE TABLE TRIP3 (
               RIDE_ID INT PRIMARY KEY,
               DRIVER_ID INT NOT NULL,                     -- not null doesn't acpt the null values
               RIDER_ID INT ,
               PICKUP_LOCATION VARCHAR (100) NOT NULL ,
               DROPOFF_LOCATION VARCHAR (100) NOT NULL ,
               RIDE_DATE DATETIME NOT NULL,
               FARE DECIMAL(10,2) CHECK (FARE > 0)               -- CHECK NEGATIVE VALUE
);


INSERT INTO TRIP3 (RIDE_ID,DRIVER_ID,RIDER_ID,PICKUP_LOCATION,DROPOFF_LOCATION,RIDE_DATE,FARE)
VALUE 
(3,121,201,'K.K NAGAR','TAMBARAM','2024-12-29 08:00:00',500.00); 
INSERT INTO TRIP3 (RIDE_ID,DRIVER_ID,RIDER_ID,PICKUP_LOCATION,DROPOFF_LOCATION,RIDE_DATE,FARE)
VALUE 
(4,121,201,'K.K NAGAR','TAMBARAM','2024-12-29 08:00:00',-100.00);    -- IT SHOW ERROR BCOZ OF NEGATIVE VALUE3 IN FARE

INSERT INTO TRIP3 (RIDE_ID,DRIVER_ID,RIDER_ID,PICKUP_LOCATION,DROPOFF_LOCATION,RIDE_DATE,FARE)
VALUE 
(5,121,201,'K.K NAGAR','TAMBARAM','2024-12-29 08:00:00',800.00); 


SELECT *FROM TRIP3;



-- FOREIGN KEY

USE UBER;

DROP TABLE IF exists RIDE;
create table drivers (
 driver_id int primary key,
 driver_name varchar (100),
 license_number varchar (50) unique
);


create table ride(
  rider_id int primary key,
  driver_id int,
  pickup_location varchar (100),
  dropoff_location varchar (100),
  foreign key(driver_id) references drivers (driver_id)
);


INSERT INTO  DRIVERS (DRIVER_ID,DRIVER_NAME,LICENSE_NUMBER)
VALUE 
(101,'AAA','XYZ123'),
(102,'BBB','ABCDEF');

INSERT INTO RIDE (RIDER_ID,DRIVER_ID,PICKUP_LOCATION,DROPOFF_LOCATION)
VALUES
(1,101,'VELACHERRY','CROMPET'),
(2,101,'TAMBARAM','VILLIVAKAM'),
(3,102,'SINGAPERMALKOVIL','SAIDAPET');


SELECT *FROM DRIVERS;

SELECT *FROM RIDE;

INSERT INTO RIDE (RIDER_ID,DRIVER_ID,PICKUP_LOCATION,DROPOFF_LOCATION)
VALUES
(4,103,'VELACHERRY','CROMPET');                 -- Cannot add or update a child row: a foreign key constraint fails (`uber`.`ride`, CONSTRAINT `ride_ibfk_1` FOREIGN KEY (`driver_id`) REFERENCES `drivers` (`driver_id`))	0.016 sec
                                                -- ILLATHA FOREIGN KEY INSERT AAGATHU
                                                
                                                
                                                
DELETE FROM DRIVERS WHERE DRIVER_ID = 101;			-- ITHU FORIEGN KEY AH IRRUKURATHU NALA ITHA DELETE AAGATHU LINK TABLE LA DELETE PANNA ITHULA PANNALAM			


DELETE FROM RIDE WHERE DRIVER_ID = 101;					

DELETE FROM RIDE WHERE DRIVER_ID = 102;	

DELETE FROM DRIVERS WHERE DRIVER_ID = 102;	


TRUNCATE TABLE RIDE;

TRUNCATE TABLE DRIVERS;


-- ON DELETE CASCADE
DROP TABLE IF EXISTS DRIVERS1;
DROP TABLE IF EXISTS RIDE1;
create table drivers1 (
 driver_id int primary key,
 driver_name varchar (100),
 license_number varchar (50) unique
);


create table ride1(
  rider_id int primary key,
  driver_id int,
  pickup_location varchar (100),
  dropoff_location varchar (100),
  foreign key(driver_id) references drivers1 (driver_id)ON DELETE CASCADE        -- DELETE in parent table = related rows delete in child table
);

INSERT INTO  DRIVERS1 (DRIVER_ID,DRIVER_NAME,LICENSE_NUMBER)
VALUE 
(101,'AAA','XYZ123'),
(102,'BBB','ABCDEF');


INSERT INTO RIDE1 (RIDER_ID,DRIVER_ID,PICKUP_LOCATION,DROPOFF_LOCATION)
VALUES
(1,101,'VELACHERRY','CROMPET'),
(2,101,'TAMBARAM','VILLIVAKAM'),
(3,102,'SINGAPERMALKOVIL','SAIDAPET');


SELECT *FROM DRIVERS1;

SELECT *FROM RIDE1;

                                                            -- ON DELETE CASCADE:
                                                            -- Parent table row delete panna,
                                                            -- related child table rows automatic ah delete aagum.


DELETE FROM DRIVERS1 WHERE DRIVER_ID = 101;    

